name: Smoke test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run test
      run: python3 main.py --commits --token ${{ secrets.TEST_TOKEN_GITHUB }} --list  (list - строка пути к txt файлу со списком репозиториев) --out] out.csv --branch all
