name: Smoke test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Create list.txt
      run: echo "OSLL/github_repo_commitment_calc" > list.txt

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run test
      run: python3 main.py --commits --token ${{ secrets.TEST_TOKEN_GITHUB }} --list list.txt --out out.csv --branch master

    - name: Check if out.csv exists
      run: ls out.csv

    - name: Fail is out.csv does not exist
      if: failure()
      run: exit 1

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: out.csv
